language: node_js
sudo: false

node_js:
  - 6.1

before_install:
  - echo '//cel-npm-registry.mybluemix.net/:_authToken="beiMBXVNB2404QftDvDKj+FVDoO3EYhdsL1MUk5/6HM="' > .npmrc

install:
  - npm install

script:
  - npm run dist